runtime: python37

handlers:
  - url: /
    script: main.app
  - url: /predict
    script: main.app

env_variables:
  CLOUD_SQL_USERNAME: gtw
  CLOUD_SQL_PASSWORD: gtw
  CLOUD_SQL_DATABASE_NAME: gtw
  CLOUD_SQL_CONNECTION_NAME: gtw
